(source gnu)
(source melpa)
(source marmalade)

(depends-on "helm")
(depends-on "helm-ls-git")
(depends-on "helm-ag")
(depends-on "magit")
(depends-on "auto-complete")
(depends-on "flycheck")
(depends-on "git-gutter-fringe")
(depends-on "popup")
(depends-on "popwin")
(depends-on "expand-region")
(depends-on "anzu")
(depends-on "multiple-cursors")
(depends-on "rainbow-delimiters")
(depends-on "exec-path-from-shell")

(depends-on "js2-mode")
(depends-on "json-mode")
(depends-on "less-css-mode")
(depends-on "puppet-mode")
(depends-on "markdown-mode")

(depends-on "rhtml-mode")
(depends-on "rubocop")
(depends-on "ruby-block")
(depends-on "ruby-electric")
(depends-on "ruby-end")
